### ISSUE TITLE
component CircleCategoryNav

### ISSUE THREAD

**Issue by shota8888** [AirouTUS/shinkan-app#5]
path: @/components/CircleButton.vue
運動/文化サークルページに飛ぶボタンファイルの作成

**Comment by coco-tyw** [comment]
path: @/components/CircleCategoryNav.vue
props: 
  color: backgroundColor: String
  title: categoryTitle: String
  icon: iconNama: String
content: サークルカテゴリーページへの推移リンク

**Comment by coco-tyw** [comment]
branch: feature/circle-category-nav
